### ISSUE TITLE
`isIdentifier` has changed since PHP7.1

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Consistency#12]
See https://github.com/tagua-vm/parser/pull/31#discussion_r71005084.

**Comment by Pierozi** [comment]
FYI : Here's the concerned regex
```php
        return 0 !== preg_match(
            '#^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$#',
            $id
        );
```

I don't understand why full extended ASCII table are authorized **0x7F** - **0xFF**
but something like **0x5F { _ }** are not.

Otherwise we can use **0x20-0xFF** with exception of **0x7F**

I understand **0x7F { DEL }** was here because is taged as `printable` ascii table.

**Comment by Hywan** [comment]
We should just drop `0x7f` in favor to `0x80`. This is the new interval.
