### ISSUE TITLE
How to disable the autoloader?

### ISSUE THREAD

**Issue by mnapoli** [hoaproject/Consistency#13]
Hi,

This package is installed because it's a dependency of a dependency. It registers automatically an autoloader that we don't need (we use Composer), is there a way to not always register this autoloader?

**Comment by Hywan** [comment]
Hello :-),

I am afraid you cannot. Hoa has a default autoloader and we need it. This is not intrusive though and you should not have any conflicts with Composer. Why do you want to remove it?

**Comment by mnapoli** [comment]
To be honest with you it appeared in Blackfire profilings, but then I realized that I was profiling with Composer dump `-o` and in the `prod` environment *but* with debug enabled (Symfony)… :p So after disabling debug it doesn't look like a problem anymore.

However the time spent in the `Consistency` class could still be avoided in dev/tests if there was a way to disable it, but it's less critical than if it was in production.

I can't share the whole profile but here is a screenshot of the autoloading part (**when debug was enabled**):

![capture d ecran 2016-08-10 a 15 42 33](https://cloud.githubusercontent.com/assets/720328/17555815/43c5707e-5f11-11e6-9d64-e6c1aaa96785.png)

And if I search for `Consistency`:

![capture d ecran 2016-08-10 a 15 42 51](https://cloud.githubusercontent.com/assets/720328/17555821/4ce63d64-5f11-11e6-8de4-8c8f66c7f8dc.png)

In total there is maybe around 10ms spent in this Hoa class. As I said it's not a big issue, but it's still too bad.

**Comment by Hywan** [comment]
I reckon the time spent might be because of the autoloading. So depending where your autoloading is positioned in the autoloader stack, `Hoa\Consistency\Autoloader` might receive a lot of request, just like the one from Composer.

And this suggestion looks to be confirmed according to your profile. `Hoa\Consistency\Autoloader` is called 348x, which is the same for `…\Debug\DebugClassLoader`. So it doubly confirmes that this “issue” is strictly related to your debugging environment.

Yes, this is sad to not being able to disable Hoa's autoloader but it is required. Hoa is not always used or deployed in conjunction with Composer, so it must embed its own PSR-4 autoloader. However, it also requires to be enable because of flexible entities, which is mechanism ensuring forward and backward compatibility inside Hoa's libraries. This is a thin mechanism with a low memory footprint, … except in some edge cases like yours.

What you could do is to remove Hoa's autoloader and then re-add but after `…\Debug\DebugClassLoader`. Try this:
```php
foreach (spl_autoload_functions() as $autoloader) {
    if (is_array($autoloader) && $autoloader[0] instanceof Hoa\Consistency\Autoloader) {
        $autoloader[0]->unregister();
        $autoloader[0]->register();
    }
}
```

If you know any mechanism to load Hoa after all your Composer dependencies, that would be better too.

Did I answer your question?

**Comment by mnapoli** [comment]
Thanks for the answer

**Comment by Hywan** [comment]
Are you satisfied with this answer? If no, how could we progress?

**Comment by mnapoli** [comment]
The thing is it's a very minor problem (I'm not sure it's a problem at all), and I don't see how to progress and I don't even really need a solution so I'd rather not take up your time that could be better spent ;)

**Comment by Hywan** [comment]
@mnapoli Simple curiosity: What is the project you're using?

**Comment by mnapoli** [comment]
We are using Rulerz at Wizaplace (for pricing promotion rules)
